### ISSUE TITLE
crash, color picker

### ISSUE THREAD

**Issue by purr100** [StewartLynch/Mesh-Background-Creator#1]
The app crashes when you move the cursor near or outside the color picker panel border. Sharing it here in case anyone's interested in solving it. 
[crash report.txt](https://github.com/user-attachments/files/16172807/crash.txt)

https://github.com/StewartLynch/Mesh-Background-Creator/assets/161710440/55612737-8cd8-48b7-8dcf-feaab186aba7

**Comment by StewartLynch** [comment]
Very interesting.  I never use Spectrum so I never noticed that.  Seems like it is an Apple bug to me.
Let me see what I can discover

**Comment by StewartLynch** [comment]
I found my bug. It was in my luminance code.  Fixed in the latest version
